### ISSUE TITLE
Json support ?

### ISSUE THREAD

**Issue by hfawaz** [dberenbaum/hydra-dvc-multirun#1]
Very useful example thank you so much for sharing! 

Any idea howto make it work with json ?

**Comment by dberenbaum** [comment]
Sorry, there's no json support right now. Do you want to use json for the hydra conf directory, or for the final parameters file that gets generated, or both?

For the hydra conf directory, you are probably stuck with yaml, or you would at least need to ask the hydra maintainers to start supporting json.

**Comment by hfawaz** [comment]
I agree should check with Hydra maintainers thanks !
